### ISSUE TITLE
   运行结果是成功，其实没有更新ip

### ISSUE THREAD

**Issue by 365v** [ddgth/cf2dns#157]
https://github.com/365v/cf2dns/actions

Annotations
1 warning
build
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, actions/setup-python@v4. For more info:
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by ddgth** [comment]
> https://github.com/365v/cf2dns/actions
> 
> Annotations 1 warning build The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, actions/setup-python@v4. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

https://github.com/365v/cf2dns/actions/runs/11437609833/job/31817460887

```
Traceback (most recent call last):
  File "/home/runner/work/cf2dns/cf2dns/dns/qCloud.py", line 54, in get_record
    resp = client.DescribeRecordList(req_model)
CHANGE DNS ERROR: ----Time: 2024-10-21 09:51:41----MESSAGE: None
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/tencentcloud/dnspod/v20210323/dnspod_client.py", line 891, in DescribeRecordList
    raise TencentCloudSDKException(code, message, reqid)
tencentcloud.common.exception.tencent_cloud_sdk_exception.TencentCloudSDKException: [TencentCloudSDKException] code:OperationDenied.NoPermissionToOperateDomain message:当前域名无权限，请返回域名列表。 requestId:821[19](https://github.com/365v/cf2dns/actions/runs/11437609833/job/31817460887#step:5:20)5e8-ca5b-4df4-9615-dfd898527e17
```

有报错  检查DOMAIN 配置是否正常

**Comment by 365v** [comment]
![c0d44786-ca9a-4460-a33a-7b6d2d208d4c](https://github.com/user-attachments/assets/433b5751-4020-4cf5-bf4d-3df6d866043b)
![7dea8cc4-b0a1-42fd-8a63-98d2f2af6f69](https://github.com/user-attachments/assets/47ef9869-4a99-4fd4-a4d2-0f00a2ab1838)


同时 更新v4  和v6  这没问题吧？

**Comment by 365v** [comment]
好了，谢谢，
