### ISSUE TITLE
直接Fork的按照教程中修改，但是报了错误，麻烦请看看是怎么回事

### ISSUE THREAD

**Issue by Mydong** [ddgth/cf2dns#82]
![image](https://user-images.githubusercontent.com/14023137/153551659-00b0f790-28f8-44d8-b77a-ecccb9053750.png)

```
Run python cf2dns_actions.py
Traceback (most recent call last):
  File "cf2dns_actions.py", line 22, in <module>
    DOMAINS = json.loads(os.environ["DOMAINS"])  #{"hostmonit.com": {"@": ["CM","CU","CT"], "shop": ["CM", "CU", "CT"], "stock": ["CM","CU","CT"]},"4096.me": {"@": ["CM","CU","CT"], "vv": ["CM","CU","CT"]}}
  File "/opt/hostedtoolcache/Python/3.7.[12](https://github.com/Mydong/cf2dns/runs/5152771209?check_suite_focus=true#step:5:12)/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 90 (char 89)
Error: Process completed with exit code 1.
```

**Comment by ddgth** [comment]
重新配置下DOMAINS，KEY，SECRETID，SECRETKEY 再试下
