### ISSUE TITLE
运行后爆了一个错误能看看啥情况吗

### ISSUE THREAD

**Issue by yangshuilo** [ddgth/cf2dns#84]
![3333](https://user-images.githubusercontent.com/100583116/155987810-ce61c76b-dec6-41bf-9c0d-8903a9e4f7a7.jpg)
![4444](https://user-images.githubusercontent.com/100583116/155987819-6203e55b-17c5-4f76-a24d-3f829e55e123.jpg)

Run python cf2dns_actions.py
Traceback (most recent call last):
CHANGE DNS ERROR: ----Time: 2022-02-28 12:55:33----MESSAGE: None
  File "cf2dns_actions.py", line [11](https://github.com/yangshuilo/cf2dns/runs/5359794770?check_suite_focus=true#step:5:11)7, in main
    ret = cloud.get_record(domain, 20, sub_domain, "CNAME")
  File "/home/runner/work/cf2dns/cf2dns/dns/qCloud.py", line 56, in get_record
    return self.get(module = 'cns', action = 'RecordList', domain = domain, length = length, subDomain = sub_domain, recordType = record_type)
  File "/home/runner/work/cf2dns/cf2dns/dns/qCloud.py", line 50, in get
    raise Exception(ret)
Exception: {'code': 5100, 'message': '(8)服务内部错误，请稍后重试或联系客服人员解决。', 'codeDesc': 'ResourceOpFailed'}

**Comment by ddgth** [comment]
之前有运行成功过吗？  如果没有 可能是SECRETID，SECRETKEY设置的有问题。
