### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by fengguowudi** [ddgth/cf2dns#85]
Traceback (most recent call last):
  File "cf2dns_actions.py", line 118, in main
CHANGE DNS ERROR: ----Time: 2022-04-29 11:[17](https://github.com/fengguowudi/cf2dns/runs/6227156759?check_suite_focus=true#step:5:17):32----MESSAGE: None
    ret = cloud.get_record(domain, 20, sub_domain, "CNAME")
  File "/home/runner/work/cf2dns/cf2dns/dns/qCloud.py", line 56, in get_record
    return self.get(module = 'cns', action = 'RecordList', domain = domain, length = length, subDomain = sub_domain, recordType = record_type)
  File "/home/runner/work/cf2dns/cf2dns/dns/qCloud.py", line 50, in get
    raise Exception(ret)
Exception: {'code': 5100, 'message': '(7)服务内部错误，请稍后重试或联系客服人员解决。', 'codeDesc': 'ResourceOpFailed'}

**Comment by ddgth** [comment]
检查DOMAINS，KEY，SECRETID，SECRETKEY 参数， 确保DOMAINS中填写的域名在账户中存在
