### ISSUE TITLE
action运行错误

### ISSUE THREAD

**Issue by kingvenlee** [ddgth/cf2dns#89]
Run python cf2dns_actions.py
Traceback (most recent call last):
  File "cf2dns_actions.py", line 22, in <module>
    DOMAINS = json.loads(os.environ["DOMAINS"])  #{"hostmonit.com": {"@": ["CM","CU","CT"], "shop": ["CM", "CU", "CT"], "stock": ["CM","CU","CT"]},"4096.me": {"@": ["CM","CU","CT"], "vv": ["CM","CU","CT"]}}
  File "/opt/hostedtoolcache/Python/3.7.[13](https://github.com/kingvenlee/cf2dns/runs/6481121320?check_suite_focus=true#step:5:14)/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.

**Comment by kingvenlee** [comment]
我感觉可能的原因时添加secret的方式跟README里面描述的不一样。
github可能更新了这块，但是不知道具体哪里出了问题。我的secret在environment里面加的

**Comment by ddgth** [comment]
DOMAINS域名参数添加的有问题

**Comment by fulldao** [comment]
> 我感觉可能的原因时添加secret的方式跟README里面描述的不一样。 github可能更新了这块，但是不知道具体哪里出了问题。我的secret在environment里面加的

github更新过secret的添加方式，所以看起来会和大佬README里的描述不一样。参考下图：

![secret](https://user-images.githubusercontent.com/24914557/169504910-a7c3d1bb-d9a9-4015-8648-1135347e856d.png)

不过就算是你成功运行了，Ations的schedule也很不准时（它等于只是按时给你的Ations叫了个排队运行的号，等排到你才会正式运行，至于什么时候能排到你，就很难说了），想要准时运行的话，需要修改代码，再配合其它云的定时任务来调用。
按照方式一，在自己的vps里运行会简单一些。
